
language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    - build-tools-24.0.2
    - android-25
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-17
before_script:
    - mkdir -p "$ANDROID_HOME/licenses"
    - cp ./android-licenses/* "$ANDROID_HOME/licenses/"
before_install:
 - chmod +x gradlew
script:
    - ./gradlew build check
